export const TREE_LEVELS = [
  { level: 1, label: 'Brote', thoughts: 0, likes: 0, days: 0 },
  { level: 2, label: 'Arbolito', thoughts: 5, likes: 10, days: 3 },
  { level: 3, label: 'Árbol Joven', thoughts: 15, likes: 30, days: 7 },
  { level: 4, label: 'Árbol Fuerte', thoughts: 30, likes: 70, days: 15 },
  { level: 5, label: 'Árbol Sabio', thoughts: 50, likes: 120, days: 30 },
  { level: 6, label: 'Árbol Ancestral', thoughts: 100, likes: 250, days: 60 },
  { level: 7, label: 'Árbol Centenario', thoughts: 150, likes: 400, days: 90 },
  { level: 8, label: 'Árbol Guardián', thoughts: 200, likes: 550, days: 120 },
  { level: 9, label: 'Bosque Joven', thoughts: 275, likes: 750, days: 150 },
  { level: 10, label: 'Bosque Profundo', thoughts: 350, likes: 1000, days: 180 },
  { level: 15, label: 'Bosque Maduro', thoughts: 500, likes: 1500, days: 240 },
  { level: 20, label: 'Bosque Ancestral', thoughts: 750, likes: 2200, days: 300 },
  { level: 25, label: 'Árbol de Cristal', thoughts: 1000, likes: 3000, days: 365 },
  { level: 30, label: 'Bosque de Cristal', thoughts: 1300, likes: 4000, days: 420 },
  { level: 35, label: 'Árbol de Estrellas', thoughts: 1600, likes: 5000, days: 480 },
  { level: 40, label: 'Bosque Estelar', thoughts: 2000, likes: 6500, days: 540 },
  { level: 45, label: 'Árbol Cósmico', thoughts: 2500, likes: 8000, days: 600 },
  { level: 50, label: 'Bosque Cósmico', thoughts: 3000, likes: 10000, days: 660 },
  { level: 60, label: 'Nebulosa Arbórea', thoughts: 4000, likes: 12500, days: 730 },
  { level: 70, label: 'Constelación de Hojas', thoughts: 5500, likes: 15000, days: 800 },
  { level: 80, label: 'Árbol Divino', thoughts: 7000, likes: 18000, days: 880 },
  { level: 90, label: 'Bosque Celestial', thoughts: 8500, likes: 22000, days: 960 },
  { level: 101, label: 'Árbol del Universo', thoughts: 10000, likes: 25000, days: 1000 },
];

export const PRIZES = [
  {
    id: 'christmas_thought',
    title: 'Espíritu Navideño',
    description: '¡Has escrito un pensamiento en Navidad! ¡Felices fiestas!',
    icon: '🎄',
    color: '#C63D3D', // Red
    category: 'special-day',
    isUnlocked: (stats) => {
      const today = new Date();
      return stats?.thoughts > 0 && today.getMonth() === 11 && today.getDate() === 25;
    },
    level: 1,
  },
  {
    id: 'new_year_thought',
    title: 'Nuevo Comienzo',
    description: '¡Un pensamiento para empezar el Año Nuevo con la mejor energía!',
    icon: '🎉',
    color: '#FFD700', // Gold
    category: 'special-day',
    isUnlocked: (stats) => {
      const today = new Date();
      return stats?.thoughts > 0 && today.getMonth() === 0 && today.getDate() === 1;
    },
    level: 1,
  },
  {
    id: 'valentines_thought',
    title: 'Amor y Amistad',
    description: '¡Compartiste un pensamiento en San Valentín! ¡Que viva el amor!',
    icon: '💖',
    color: '#FF69B4', // Hot Pink
    category: 'special-day',
    isUnlocked: (stats) => {
      const today = new Date();
      return stats?.thoughts > 0 && today.getMonth() === 1 && today.getDate() === 14;
    },
    level: 1,
  },
  {
    id: 'thoughts_1',
    title: 'Primera Idea',
    description: 'Has escrito 1 pensamiento. ¡Tu mente es imparable!',
    icon: 'lightbulb-outline',
    color: '#FFD700',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 1,
    level: 1,
  },
  {
    id: 'thoughts_5',
    title: 'Mente Despierta',
    description: 'Has escrito 5 pensamientos. ¡Tu mente es imparable!',
    icon: 'lightbulb-on-outline',
    color: '#FFD700',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 5,
    level: 1,
  },
  {
    id: 'thoughts_10',
    title: 'Rueda de Ideas',
    description: 'Has escrito 10 pensamientos. ¡Tu mente es imparable!',
    icon: 'brain',
    color: '#8A2BE2',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 10,
    level: 1,
  },
  {
    id: 'thoughts_25',
    title: 'Faro del Pensamiento',
    description: 'Has escrito 25 pensamientos. ¡Tu mente es imparable!',
    icon: 'head-lightbulb-outline',
    color: '#8A2BE2',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 25,
    level: 1,
  },
  {
    id: 'thoughts_50',
    title: 'Nube de Ideas',
    description: 'Has escrito 50 pensamientos. ¡Tu mente es imparable!',
    icon: 'thought-bubble-outline',
    color: '#8A2BE2',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 50,
    level: 1,
  },
  {
    id: 'thoughts_100',
    title: 'Diario del Alma',
    description: 'Has escrito 100 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-open-page-variant-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 100,
    level: 2,
  },
  {
    id: 'thoughts_200',
    title: 'Crónicas Mentales',
    description: 'Has escrito 200 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-multiple-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 200,
    level: 3,
  },
  {
    id: 'thoughts_300',
    title: 'Biblioteca Interior',
    description: 'Has escrito 300 pensamientos. ¡Tu mente es imparable!',
    icon: 'library',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 300,
    level: 4,
  },
  {
    id: 'thoughts_400',
    title: 'Pluma de Oro',
    description: 'Has escrito 400 pensamientos. ¡Tu mente es imparable!',
    icon: 'fountain-pen-tip',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 400,
    level: 5,
  },
  {
    id: 'thoughts_500',
    title: 'Máquina de Ideas',
    description: 'Has escrito 500 pensamientos. ¡Tu mente es imparable!',
    icon: 'typewriter',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 500,
    level: 6,
  },
  {
    id: 'thoughts_750',
    title: 'Cálamo del Saber',
    description: 'Has escrito 750 pensamientos. ¡Tu mente es imparable!',
    icon: 'pen',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 750,
    level: 8,
  },
  {
    id: 'thoughts_1000',
    title: 'Papiro Ancestral',
    description: 'Has escrito 1000 pensamientos. ¡Tu mente es imparable!',
    icon: 'script-text-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 1000,
    level: 11,
  },
  {
    id: 'thoughts_1250',
    title: 'Cuaderno Infinito',
    description: 'Has escrito 1250 pensamientos. ¡Tu mente es imparable!',
    icon: 'notebook-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 1250,
    level: 13,
  },
  {
    id: 'thoughts_1500',
    title: 'Bitácora del Pensador',
    description: 'Has escrito 1500 pensamientos. ¡Tu mente es imparable!',
    icon: 'notebook',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 1500,
    level: 16,
  },
  {
    id: 'thoughts_1750',
    title: 'Enciclopedia Mental',
    description: 'Has escrito 1750 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-education-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 1750,
    level: 18,
  },
  {
    id: 'thoughts_2000',
    title: 'Saga de Pensamientos',
    description: 'Has escrito 2000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-open-page-variant',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 2000,
    level: 21,
  },
  {
    id: 'thoughts_2500',
    title: 'Códice del Saber',
    description: 'Has escrito 2500 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-cross',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 2500,
    level: 26,
  },
  {
    id: 'thoughts_3000',
    title: 'Archivo de la Mente',
    description: 'Has escrito 3000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-multiple-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 3000,
    level: 31,
  },
  {
    id: 'thoughts_3500',
    title: 'Volumen Infinito',
    description: 'Has escrito 3500 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-open-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 3500,
    level: 36,
  },
  {
    id: 'thoughts_4000',
    title: 'Colección de Ideas',
    description: 'Has escrito 4000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-variant-multiple',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 4000,
    level: 41,
  },
  {
    id: 'thoughts_4500',
    title: 'Buscador de Verdades',
    description: 'Has escrito 4500 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-search-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 4500,
    level: 46,
  },
  {
    id: 'thoughts_5000',
    title: 'Guardián de la Sabiduría',
    description: 'Has escrito 5000 pensamientos. ¡Tu mente es imparable!',
    icon: 'bookshelf',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 5000,
    level: 51,
  },
  {
    id: 'thoughts_6000',
    title: 'Archivero del Pensamiento',
    description: 'Has escrito 6000 pensamientos. ¡Tu mente es imparable!',
    icon: 'library-shelves',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 6000,
    level: 61,
  },
  {
    id: 'thoughts_7000',
    title: 'Cronista de la Mente',
    description: 'Has escrito 7000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-account-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 7000,
    level: 71,
  },
  {
    id: 'thoughts_8000',
    title: 'Verificador de Ideas',
    description: 'Has escrito 8000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-check-outline',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 8000,
    level: 81,
  },
  {
    id: 'thoughts_9000',
    title: 'Corazón Pensante',
    description: 'Has escrito 9000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-heart',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 9000,
    level: 91,
  },
  {
    id: 'thoughts_10000',
    title: 'Mente Maestra',
    description: 'Has escrito 10000 pensamientos. ¡Tu mente es imparable!',
    icon: 'book-open-blank-variant',
    color: '#4682B4',
    category: 'thought-count',
    isUnlocked: (stats) => stats?.thoughts >= 10000,
    level: 101,
  },
  {
    id: 'likes_1',
    title: 'Primer Aplauso',
    description: '¡1 like! Tus pensamientos resuenan en la comunidad.',
    icon: 'thumb-up-outline',
    color: '#20B2AA',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 1,
    level: 1,
  },
  {
    id: 'likes_5',
    title: 'Pulgar Arriba',
    description: '¡5 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'thumb-up',
    color: '#20B2AA',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 5,
    level: 1,
  },
  {
    id: 'likes_10',
    title: 'Corazón Conectado',
    description: '¡10 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'heart-outline',
    color: '#FF69B4',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 10,
    level: 1,
  },
  {
    id: 'likes_25',
    title: 'Latido Compartido',
    description: '¡25 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'heart',
    color: '#FF69B4',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 25,
    level: 1,
  },
  {
    id: 'likes_50',
    title: 'Estrella Naciente',
    description: '¡50 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'star-outline',
    color: '#FFD700',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 50,
    level: 1,
  },
  {
    id: 'likes_100',
    title: 'Cien Estrellas',
    description: '¡100 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'star',
    color: '#FFD700',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 100,
    level: 2,
  },
  {
    id: 'likes_200',
    title: 'Medalla de Bronce',
    description: '¡200 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'medal-outline',
    color: '#CD7F32',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 200,
    level: 3,
  },
  {
    id: 'likes_300',
    title: 'Medalla Brillante',
    description: '¡300 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'medal',
    color: '#CD7F32',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 300,
    level: 4,
  },
  {
    id: 'likes_400',
    title: 'Copa Plateada',
    description: '¡400 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'trophy-outline',
    color: '#C0C0C0',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 400,
    level: 5,
  },
  {
    id: 'likes_500',
    title: 'Trofeo de Plata',
    description: '¡500 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'trophy',
    color: '#C0C0C0',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 500,
    level: 6,
  },
  {
    id: 'likes_750',
    title: 'Corona Dorada',
    description: '¡750 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'crown-outline',
    color: '#FFD700',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 750,
    level: 8,
  },
  {
    id: 'likes_1000',
    title: 'Rey de Corazones',
    description: '¡1000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'crown',
    color: '#FFD700',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 1000,
    level: 11,
  },
  {
    id: 'likes_1250',
    title: 'Diamante Pulido',
    description: '¡1250 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'diamond-outline',
    color: '#B9F2FF',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 1250,
    level: 13,
  },
  {
    id: 'likes_1500',
    title: 'Gema Preciosa',
    description: '¡1500 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'diamond',
    color: '#B9F2FF',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 1500,
    level: 16,
  },
  {
    id: 'likes_1750',
    title: 'Zafiro Brillante',
    description: '¡1750 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'diamond-stone',
    color: '#00CED1',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 1750,
    level: 18,
  },
  {
    id: 'likes_2000',
    title: 'Esmeralda Resplandeciente',
    description: '¡2000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'diamond',
    color: '#00CED1',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 2000,
    level: 21,
  },
  {
    id: 'likes_2500',
    title: 'Cofre del Tesoro',
    description: '¡2500 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'treasure-chest',
    color: '#8B4513',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 2500,
    level: 26,
  },
  {
    id: 'likes_3000',
    title: 'Bóveda de Riquezas',
    description: '¡3000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'safe-square-outline',
    color: '#8B4513',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 3000,
    level: 31,
  },
  {
    id: 'likes_3500',
    title: 'Fortuna Acumulada',
    description: '¡3500 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'safe-square',
    color: '#8B4513',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 3500,
    level: 36,
  },
  {
    id: 'likes_4000',
    title: 'Cámara Acorazada',
    description: '¡4000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'safe',
    color: '#8B4513',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 4000,
    level: 41,
  },
  {
    id: 'likes_4500',
    title: 'Banco de la Felicidad',
    description: '¡4500 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'bank-outline',
    color: '#8B4513',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 4500,
    level: 46,
  },
  {
    id: 'likes_5000',
    title: 'Capital de la Alegría',
    description: '¡5000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'bank',
    color: '#8B4513',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 5000,
    level: 51,
  },
  {
    id: 'likes_6000',
    title: 'Hucha Llena',
    description: '¡6000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'piggy-bank-outline',
    color: '#FFC0CB',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 6000,
    level: 61,
  },
  {
    id: 'likes_7000',
    title: 'Cerdo Ahorrador',
    description: '¡7000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'piggy-bank',
    color: '#FFC0CB',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 7000,
    level: 71,
  },
  {
    id: 'likes_8000',
    title: 'Lluvia de Monedas',
    description: '¡8000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'cash-multiple',
    color: '#32CD32',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 8000,
    level: 81,
  },
  {
    id: 'likes_9000',
    title: 'Dólares de Felicidad',
    description: '¡9000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'currency-usd',
    color: '#32CD32',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 9000,
    level: 91,
  },
  {
    id: 'likes_10000',
    title: 'Saco de Oro',
    description: '¡10000 likes! Tus pensamientos resuenan en la comunidad.',
    icon: 'sack-percent',
    color: '#32CD32',
    category: 'like-count',
    isUnlocked: (stats) => stats?.likes >= 10000,
    level: 101,
  },
  {
    id: 'days_1',
    title: 'Primer Amanecer',
    description: 'Has estado activo por 1 día. ¡Un hábito saludable!',
    icon: 'calendar-today',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 1,
    level: 1,
  },
  {
    id: 'days_3',
    title: 'Fin de Semana Activo',
    description: 'Has estado activo por 3 días. ¡Un hábito saludable!',
    icon: 'calendar-range',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 3,
    level: 1,
  },
  {
    id: 'days_7',
    title: 'Semana Completa',
    description: 'Has estado activo por 7 días. ¡Un hábito saludable!',
    icon: 'calendar-week',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 7,
    level: 1,
  },
  {
    id: 'days_14',
    title: 'Quincena Constante',
    description: 'Has estado activo por 14 días. ¡Un hábito saludable!',
    icon: 'calendar-month',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 14,
    level: 1,
  },
  {
    id: 'days_30',
    title: 'Mes de Dedicación',
    description: 'Has estado activo por 30 días. ¡Un hábito saludable!',
    icon: 'calendar-check',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 30,
    level: 1,
  },
  {
    id: 'days_60',
    title: 'Doble Mes',
    description: 'Has estado activo por 60 días. ¡Un hábito saludable!',
    icon: 'calendar-star',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 60,
    level: 2,
  },
  {
    id: 'days_90',
    title: 'Trimestre de Hábito',
    description: 'Has estado activo por 90 días. ¡Un hábito saludable!',
    icon: 'calendar-heart',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 90,
    level: 2,
  },
  {
    id: 'days_120',
    title: 'Cuatro Meses Firmes',
    description: 'Has estado activo por 120 días. ¡Un hábito saludable!',
    icon: 'calendar-plus',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 120,
    level: 3,
  },
  {
    id: 'days_150',
    title: 'Cinco Meses de Paz',
    description: 'Has estado activo por 150 días. ¡Un hábito saludable!',
    icon: 'calendar-text',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 150,
    level: 4,
  },
  {
    id: 'days_180',
    title: 'Medio Año de Crecimiento',
    description: 'Has estado activo por 180 días. ¡Un hábito saludable!',
    icon: 'calendar-edit',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 180,
    level: 4,
  },
  {
    id: 'days_210',
    title: 'Siete Meses de Luz',
    description: 'Has estado activo por 210 días. ¡Un hábito saludable!',
    icon: 'calendar-remove',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 210,
    level: 5,
  },
  {
    id: 'days_240',
    title: 'Ocho Meses de Calma',
    description: 'Has estado activo por 240 días. ¡Un hábito saludable!',
    icon: 'calendar-alert',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 240,
    level: 5,
  },
  {
    id: 'days_270',
    title: 'Nueve Meses de Armonía',
    description: 'Has estado activo por 270 días. ¡Un hábito saludable!',
    icon: 'calendar-question',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 270,
    level: 6,
  },
  {
    id: 'days_300',
    title: 'Diez Meses de Éxito',
    description: 'Has estado activo por 300 días. ¡Un hábito saludable!',
    icon: 'calendar-search',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 300,
    level: 7,
  },
  {
    id: 'days_330',
    title: 'Once Meses de Constancia',
    description: 'Has estado activo por 330 días. ¡Un hábito saludable!',
    icon: 'calendar-sync',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 330,
    level: 7,
  },
  {
    id: 'days_365',
    title: 'Año de Transformación',
    description: 'Has estado activo por 365 días. ¡Un hábito saludable!',
    icon: 'calendar-account',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 365,
    level: 8,
  },
  {
    id: 'days_400',
    title: 'Más Allá del Año',
    description: 'Has estado activo por 400 días. ¡Un hábito saludable!',
    icon: 'calendar-clock',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 400,
    level: 9,
  },
  {
    id: 'days_450',
    title: 'Un Año y Medio',
    description: 'Has estado activo por 450 días. ¡Un hábito saludable!',
    icon: 'calendar-multiple',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 450,
    level: 10,
  },
  {
    id: 'days_500',
    title: 'Quinientos Soles',
    description: 'Has estado activo por 500 días. ¡Un hábito saludable!',
    icon: 'calendar-today',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 500,
    level: 11,
  },
  {
    id: 'days_600',
    title: 'Seiscientos Días',
    description: 'Has estado activo por 600 días. ¡Un hábito saludable!',
    icon: 'calendar-range',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 600,
    level: 13,
  },
  {
    id: 'days_700',
    title: 'Setecientos Días',
    description: 'Has estado activo por 700 días. ¡Un hábito saludable!',
    icon: 'calendar-week',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 700,
    level: 15,
  },
  {
    id: 'days_800',
    title: 'Ochocientos Días',
    description: 'Has estado activo por 800 días. ¡Un hábito saludable!',
    icon: 'calendar-month',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 800,
    level: 17,
  },
  {
    id: 'days_900',
    title: 'Novecientos Días',
    description: 'Has estado activo por 900 días. ¡Un hábito saludable!',
    icon: 'calendar-check',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 900,
    level: 19,
  },
  {
    id: 'days_1000',
    title: 'Mil Días de Paz',
    description: 'Has estado activo por 1000 días. ¡Un hábito saludable!',
    icon: 'calendar-star',
    color: '#6A5ACD',
    category: 'day-count',
    isUnlocked: (stats) => stats?.days >= 1000,
    level: 21,
  },
  {
    id: 'joy_streak_5',
    title: 'Ráfaga de Alegría',
    description: '5 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-happy-outline',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 5,
    level: 1,
  },
  {
    id: 'joy_streak_10',
    title: 'Sonrisa Contagiosa',
    description: '10 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-happy',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 10,
    level: 1,
  },
  {
    id: 'joy_streak_25',
    title: 'Explosión de Felicidad',
    description: '25 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 25,
    level: 2,
  },
  {
    id: 'joy_streak_50',
    title: 'Júbilo Radiante',
    description: '50 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 50,
    level: 3,
  },
  {
    id: 'joy_streak_100',
    title: 'Cien Risas',
    description: '100 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-happy-outline',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 100,
    level: 5,
  },
  {
    id: 'joy_streak_200',
    title: 'Doscientas Sonrisas',
    description: '200 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-happy',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 200,
    level: 9,
  },
  {
    id: 'joy_streak_300',
    title: 'Trescientos Momentos Felices',
    description: '300 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 300,
    level: 13,
  },
  {
    id: 'joy_streak_400',
    title: 'Cuatrocientas Alegrías',
    description: '400 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 400,
    level: 17,
  },
  {
    id: 'joy_streak_500',
    title: 'Quinientas Carcajadas',
    description: '500 pensamientos de alegría. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-happy-outline',
    color: '#FFD700',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.joy >= 500,
    level: 21,
  },
  {
    id: 'gratitude_streak_5',
    title: 'Semilla de Gratitud',
    description: '5 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 5,
    level: 1,
  },
  {
    id: 'gratitude_streak_10',
    title: 'Corazón Agradecido',
    description: '10 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 10,
    level: 1,
  },
  {
    id: 'gratitude_streak_25',
    title: 'Cosecha de Agradecimiento',
    description: '25 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 25,
    level: 2,
  },
  {
    id: 'gratitude_streak_50',
    title: 'Jardín de Gracias',
    description: '50 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 50,
    level: 3,
  },
  {
    id: 'gratitude_streak_100',
    title: 'Cien Bendiciones',
    description: '100 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 100,
    level: 5,
  },
  {
    id: 'gratitude_streak_200',
    title: 'Doscientas Gracias',
    description: '200 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 200,
    level: 9,
  },
  {
    id: 'gratitude_streak_300',
    title: 'Trescientos Agradecimientos',
    description: '300 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 300,
    level: 13,
  },
  {
    id: 'gratitude_streak_400',
    title: 'Cuatrocientas Bendiciones',
    description: '400 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 400,
    level: 17,
  },
  {
    id: 'gratitude_streak_500',
    title: 'Quinientas Gracias',
    description: '500 pensamientos de gratitud. ¡Sigue explorando tus emociones!',
    icon: 'hand-heart',
    color: '#32CD32',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.gratitude >= 500,
    level: 21,
  },
  {
    id: 'sadness_streak_5',
    title: 'Lágrima de Comprensión',
    description: '5 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-sad-outline',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 5,
    level: 1,
  },
  {
    id: 'sadness_streak_10',
    title: 'Nube Pasajera',
    description: '10 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-sad',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 10,
    level: 1,
  },
  {
    id: 'sadness_streak_25',
    title: 'Valle de la Melancolía',
    description: '25 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 25,
    level: 2,
  },
  {
    id: 'sadness_streak_50',
    title: 'Mar de Sentimientos',
    description: '50 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 50,
    level: 3,
  },
  {
    id: 'sadness_streak_100',
    title: 'Cien Suspiros',
    description: '100 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-sad-outline',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 100,
    level: 5,
  },
  {
    id: 'sadness_streak_200',
    title: 'Doscientas Reflexiones',
    description: '200 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-sad',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 200,
    level: 9,
  },
  {
    id: 'sadness_streak_300',
    title: 'Trescientos Momentos Íntimos',
    description: '300 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 300,
    level: 13,
  },
  {
    id: 'sadness_streak_400',
    title: 'Cuatrocientas Sombras',
    description: '400 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 400,
    level: 17,
  },
  {
    id: 'sadness_streak_500',
    title: 'Quinientas Profundidades',
    description: '500 pensamientos de tristeza. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-sad-outline',
    color: '#6495ED',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.sadness >= 500,
    level: 21,
  },
  {
    id: 'anger_streak_5',
    title: 'Chispa de Fuego',
    description: '5 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry-outline',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 5,
    level: 1,
  },
  {
    id: 'anger_streak_10',
    title: 'Volcán Interior',
    description: '10 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 10,
    level: 1,
  },
  {
    id: 'anger_streak_25',
    title: 'Tormenta Emocional',
    description: '25 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry-outline',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 25,
    level: 2,
  },
  {
    id: 'anger_streak_50',
    title: 'Rayo de Furia',
    description: '50 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 50,
    level: 3,
  },
  {
    id: 'anger_streak_100',
    title: 'Cien Llamas',
    description: '100 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry-outline',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 100,
    level: 5,
  },
  {
    id: 'anger_streak_200',
    title: 'Doscientas Erupciones',
    description: '200 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 200,
    level: 9,
  },
  {
    id: 'anger_streak_300',
    title: 'Trescientos Truenos',
    description: '300 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry-outline',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 300,
    level: 13,
  },
  {
    id: 'anger_streak_400',
    title: 'Cuatrocientas Descargas',
    description: '400 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 400,
    level: 17,
  },
  {
    id: 'anger_streak_500',
    title: 'Quinientas Explosiones',
    description: '500 pensamientos de enojo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-angry-outline',
    color: '#DC143C',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.anger >= 500,
    level: 21,
  },
  {
    id: 'fear_streak_5',
    title: 'Sombra Fugaz',
    description: '5 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 5,
    level: 1,
  },
  {
    id: 'fear_streak_10',
    title: 'Susurro Nocturno',
    description: '10 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 10,
    level: 1,
  },
  {
    id: 'fear_streak_25',
    title: 'Laberinto de Inquietudes',
    description: '25 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 25,
    level: 2,
  },
  {
    id: 'fear_streak_50',
    title: 'Abismo de Dudas',
    description: '50 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 50,
    level: 3,
  },
  {
    id: 'fear_streak_100',
    title: 'Cien Escalofríos',
    description: '100 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 100,
    level: 5,
  },
  {
    id: 'fear_streak_200',
    title: 'Doscientas Sombras',
    description: '200 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 200,
    level: 9,
  },
  {
    id: 'fear_streak_300',
    title: 'Trescientos Miedos',
    description: '300 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 300,
    level: 13,
  },
  {
    id: 'fear_streak_400',
    title: 'Cuatrocientas Pesadillas',
    description: '400 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 400,
    level: 17,
  },
  {
    id: 'fear_streak_500',
    title: 'Quinientos Terrores',
    description: '500 pensamientos de miedo. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-frown-outline',
    color: '#800080',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.fear >= 500,
    level: 21,
  },
  {
    id: 'surprise_streak_5',
    title: 'Destello Inesperado',
    description: '5 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 5,
    level: 1,
  },
  {
    id: 'surprise_streak_10',
    title: 'Asombro Creciente',
    description: '10 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 10,
    level: 1,
  },
  {
    id: 'surprise_streak_25',
    title: 'Caja de Pandora',
    description: '25 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 25,
    level: 2,
  },
  {
    id: 'surprise_streak_50',
    title: 'Explosión de Novedad',
    description: '50 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 50,
    level: 3,
  },
  {
    id: 'surprise_streak_100',
    title: 'Cien Maravillas',
    description: '100 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 100,
    level: 5,
  },
  {
    id: 'surprise_streak_200',
    title: 'Doscientas Revelaciones',
    description: '200 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 200,
    level: 9,
  },
  {
    id: 'surprise_streak_300',
    title: 'Trescientos Descubrimientos',
    description: '300 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 300,
    level: 13,
  },
  {
    id: 'surprise_streak_400',
    title: 'Cuatrocientas Novedades',
    description: '400 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 400,
    level: 17,
  },
  {
    id: 'surprise_streak_500',
    title: 'Quinientas Sorpresas',
    description: '500 pensamientos de sorpresa. ¡Sigue explorando tus emociones!',
    icon: 'emoticon-excited-outline',
    color: '#FFA500',
    category: 'emotion-streak',
    isUnlocked: (stats) => stats?.emotions?.surprise >= 500,
    level: 21,
  },
  {
    id: 'ai_insight_1',
    title: 'Primer Destello IA',
    description: 'Recibiste 1 insight de la IA. ¡Sabiduría artificial en acción!',
    icon: 'robot-outline',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 1,
    level: 1,
  },
  {
    id: 'ai_insight_5',
    title: 'Conexión Robótica',
    description: 'Recibiste 5 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'robot',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 5,
    level: 1,
  },
  {
    id: 'ai_insight_10',
    title: 'Mente Sintética',
    description: 'Recibiste 10 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'brain',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 10,
    level: 1,
  },
  {
    id: 'ai_insight_25',
    title: 'Chip de Sabiduría',
    description: 'Recibiste 25 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'chip',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 25,
    level: 2,
  },
  {
    id: 'ai_insight_50',
    title: 'Procesador Brillante',
    description: 'Recibiste 50 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'cpu-32-bit',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 50,
    level: 3,
  },
  {
    id: 'ai_insight_100',
    title: 'Memoria Expandida',
    description: 'Recibiste 100 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'memory',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 100,
    level: 5,
  },
  {
    id: 'ai_insight_200',
    title: 'Servidor de Ideas',
    description: 'Recibiste 200 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'server',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 200,
    level: 9,
  },
  {
    id: 'ai_insight_300',
    title: 'Base de Datos Mental',
    description: 'Recibiste 300 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'database',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 300,
    level: 13,
  },
  {
    id: 'ai_insight_400',
    title: 'Nube de Conocimiento',
    description: 'Recibiste 400 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'cloud-braces',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 400,
    level: 17,
  },
  {
    id: 'ai_insight_500',
    title: 'Etiquetas Inteligentes',
    description: 'Recibiste 500 insights de la IA. ¡Sabiduría artificial en acción!',
    icon: 'cloud-tags',
    color: '#808080',
    category: 'ai-insight',
    isUnlocked: (stats) => stats?.insights >= 500,
    level: 21,
  },
  {
    id: 'level_up_1',
    title: 'Semilla Plantada',
    description: '¡Has alcanzado el nivel 1! Tu viaje de crecimiento comienza.',
    icon: 'seed',
    color: '#8B4513', // Saddle Brown
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 1,
    level: 1,
  },
  {
    id: 'level_up_2',
    title: 'Brote Curioso',
    description: '¡Has alcanzado el nivel 2! Tus primeras hojas se asoman.',
    icon: 'sprout',
    color: '#228B22', // Forest Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 2,
    level: 2,
  },
  {
    id: 'level_up_3',
    title: 'Raíces Fuertes',
    description: '¡Has alcanzado el nivel 3! Tu base se consolida.',
    icon: 'tree-outline',
    color: '#556B2F', // Dark Olive Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 3,
    level: 3,
  },
  {
    id: 'level_up_4',
    title: 'Primeros Tallos',
    description: '¡Has alcanzado el nivel 4! Empiezas a estirarte hacia el sol.',
    icon: 'leaf',
    color: '#6B8E23', // Olive Drab
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 4,
    level: 4,
  },
  {
    id: 'level_up_5',
    title: 'Pequeño Árbol',
    description: '¡Has alcanzado el nivel 5! Ya eres un arbolito.',
    icon: 'tree',
    color: '#006400', // Dark Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 5,
    level: 5,
  },
  {
    id: 'level_up_6',
    title: 'Ramas Jóvenes',
    description: '¡Has alcanzado el nivel 6! Tus ramas empiezan a extenderse.',
    icon: 'pine-tree',
    color: '#2E8B57', // Sea Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 6,
    level: 6,
  },
  {
    id: 'level_up_7',
    title: 'Follaje Naciente',
    description: '¡Has alcanzado el nivel 7! Tu follaje se vuelve más denso.',
    icon: 'forest',
    color: '#3CB371', // Medium Sea Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 7,
    level: 7,
  },
  {
    id: 'level_up_8',
    title: 'Copa en Formación',
    description: '¡Has alcanzado el nivel 8! Tu copa empieza a tomar forma.',
    icon: 'tree',
    color: '#008000', // Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 8,
    level: 8,
  },
  {
    id: 'level_up_9',
    title: 'Árbol Resiliente',
    description: '¡Has alcanzado el nivel 9! Resistiendo las tormentas.',
    icon: 'shield-sun-outline',
    color: '#6B8E23', // Olive Drab
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 9,
    level: 9,
  },
  {
    id: 'level_up_10',
    title: 'Universo Interior',
    description: '¡Has alcanzado el nivel 10! Un pequeño universo crece en ti.',
    icon: 'creation',
    color: '#228B22', // Forest Green
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 10,
    level: 10,
  },
  {
    id: 'level_up_11',
    title: 'Floración Inicial',
    description: '¡Has alcanzado el nivel 11! Tus primeras flores aparecen.',
    icon: 'flower',
    color: '#FF69B4', // Hot Pink
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 11,
    level: 11,
  },
  {
    id: 'level_up_12',
    title: 'Frutos Tempranos',
    description: '¡Has alcanzado el nivel 12! Empiezas a dar frutos.',
    icon: 'fruit-cherries',
    color: '#DC143C', // Crimson
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 12,
    level: 12,
  },
  {
    id: 'level_up_13',
    title: 'Crecimiento Constante',
    description: '¡Has alcanzado el nivel 13! Tu crecimiento es imparable.',
    icon: 'trending-up',
    color: '#4682B4', // Steel Blue
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 13,
    level: 13,
  },
  {
    id: 'level_up_14',
    title: 'Sol Radiante',
    description: '¡Has alcanzado el nivel 14! Brillas con luz propia.',
    icon: 'weather-sunny',
    color: '#FFD700', // Gold
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 14,
    level: 14,
  },
  {
    id: 'level_up_15',
    title: 'Luna Serena',
    description: '¡Has alcanzado el nivel 15! Encuentras calma en la noche.',
    icon: 'moon-waning-crescent',
    color: '#6A5ACD', // Slate Blue
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 15,
    level: 15,
  },
  {
    id: 'level_up_16',
    title: 'Estrella Guía',
    description: '¡Has alcanzado el nivel 16! Eres una guía para otros.',
    icon: 'star-shooting',
    color: '#ADD8E6', // Light Blue
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 16,
    level: 16,
  },
  {
    id: 'level_up_17',
    title: 'Río de Sabiduría',
    description: '¡Has alcanzado el nivel 17! Fluyes con conocimiento.',
    icon: 'water',
    color: '#4169E1', // Royal Blue
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 17,
    level: 17,
  },
  {
    id: 'level_up_18',
    title: 'Montaña Firme',
    description: '¡Has alcanzado el nivel 18! Tu fortaleza es inquebrantable.',
    icon: 'image-filter-hdr',
    color: '#A0522D', // Sienn
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 18,
    level: 18,
  },
  {
    id: 'level_up_19',
    title: 'Viento Libre',
    description: '¡Has alcanzado el nivel 19! Te mueves con libertad.',
    icon: 'weather-windy',
    color: '#B0C4DE', // Light Steel Blue
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 19,
    level: 19,
  },
  {
    id: 'level_up_20',
    title: 'Cielo Abierto',
    description: '¡Has alcanzado el nivel 20! Tu mente no tiene límites.',
    icon: 'weather-cloudy',
    color: '#87CEEB', // Sky Blue
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 20,
    level: 20,
  },
  {
    id: 'level_up_21',
    title: 'Rayo de Claridad',
    description: '¡Has alcanzado el nivel 21! La claridad ilumina tu camino.',
    icon: 'lightning-bolt',
    color: '#FFD700',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 21,
    level: 21,
  },
  {
    id: 'level_up_22',
    title: 'Gota de Lluvia',
    description: '¡Has alcanzado el nivel 22! Nutriendo tu ser.',
    icon: 'water-outline',
    color: '#6495ED',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 22,
    level: 22,
  },
  {
    id: 'level_up_23',
    title: 'Nube de Pensamientos',
    description: '¡Has alcanzado el nivel 23! Tus ideas flotan libremente.',
    icon: 'cloud',
    color: '#B0C4DE',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 23,
    level: 23,
  },
  {
    id: 'level_up_24',
    title: 'Arcoíris de Emociones',
    description: '¡Has alcanzado el nivel 24! Abrazas todas tus emociones.',
    icon: 'weather-partly-cloudy',
    color: '#FF69B4',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 24,
    level: 24,
  },
  {
    id: 'level_up_25',
    title: 'Jardín Florecido',
    description: '¡Has alcanzado el nivel 25! Tu jardín interior está en su esplendor.',
    icon: 'flower-tulip',
    color: '#FFC0CB',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 25,
    level: 25,
  },
  {
    id: 'level_up_26',
    title: 'Sembrador de Ideas',
    description: '¡Has alcanzado el nivel 26! Plantas semillas de inspiración.',
    icon: 'seed-outline',
    color: '#8B4513',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 26,
    level: 26,
  },
  {
    id: 'level_up_27',
    title: 'Cosecha Abundante',
    description: '¡Has alcanzado el nivel 27! Recoges los frutos de tu esfuerzo.',
    icon: 'corn',
    color: '#DAA520',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 27,
    level: 27,
  },
  {
    id: 'level_up_28',
    title: 'Guardián del Bosque',
    description: '¡Has alcanzado el nivel 28! Proteges tu paz interior.',
    icon: 'forest',
    color: '#228B22',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 28,
    level: 28,
  },
  {
    id: 'level_up_29',
    title: 'Sendero Iluminado',
    description: '¡Has alcanzado el nivel 29! Tu camino es claro y brillante.',
    icon: 'road-variant',
    color: '#708090',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 29,
    level: 29,
  },
  {
    id: 'level_up_30',
    title: 'Cumbre Alcanzada',
    description: '¡Has alcanzado el nivel 30! Conquistas nuevas alturas.',
    icon: 'image-filter-hdr',
    color: '#A0522D',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 30,
    level: 30,
  },
  {
    id: 'level_up_31',
    title: 'Vuelo Libre',
    description: '¡Has alcanzado el nivel 31! Tus pensamientos alzan el vuelo.',
    icon: 'bird',
    color: '#87CEEB',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 31,
    level: 31,
  },
  {
    id: 'level_up_32',
    title: 'Océano de Calma',
    description: '¡Has alcanzado el nivel 32! Encuentras serenidad en tu interior.',
    icon: 'water',
    color: '#4169E1',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 32,
    level: 32,
  },
  {
    id: 'level_up_33',
    title: 'Arena del Tiempo',
    description: '¡Has alcanzado el nivel 33! Cada grano cuenta en tu viaje.',
    icon: 'hourglass-outline',
    color: '#CD853F',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 33,
    level: 33,
  },
  {
    id: 'level_up_34',
    title: 'Brújula Interior',
    description: '¡Has alcanzado el nivel 34! Siempre encuentras tu norte.',
    icon: 'compass',
    color: '#708090',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 34,
    level: 34,
  },
  {
    id: 'level_up_35',
    title: 'Mapa de Sueños',
    description: '¡Has alcanzado el nivel 35! Trazas el camino a tus metas.',
    icon: 'map',
    color: '#DAA520',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 35,
    level: 35,
  },
  {
    id: 'level_up_36',
    title: 'Rayo de Esperanza',
    description: '¡Has alcanzado el nivel 36! Iluminas el camino para ti y otros.',
    icon: 'weather-lightning',
    color: '#FFD700',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 36,
    level: 36,
  },
  {
    id: 'level_up_37',
    title: 'Ancla de Paz',
    description: '¡Has alcanzado el nivel 37! Encuentras estabilidad en la calma.',
    icon: 'anchor',
    color: '#778899',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 37,
    level: 37,
  },
  {
    id: 'level_up_38',
    title: 'Ola de Cambio',
    description: '¡Has alcanzado el nivel 38! Te adaptas y fluyes con la vida.',
    icon: 'waves',
    color: '#4169E1',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 38,
    level: 38,
  },
  {
    id: 'level_up_39',
    title: 'Concha de Sabiduría',
    description: '¡Has alcanzado el nivel 39! Escuchas la voz de tu interior.',
    icon: 'fish',
    color: '#F5DEB3',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 39,
    level: 39,
  },
  {
    id: 'level_up_40',
    title: 'Perla Preciosa',
    description: '¡Has alcanzado el nivel 40! Un tesoro de valor incalculable.',
    icon: 'diamond-stone',
    color: '#B9F2FF',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 40,
    level: 40,
  },
  {
    id: 'level_up_41',
    title: 'Fuego Interior',
    description: '¡Has alcanzado el nivel 41! Tu pasión arde con fuerza.',
    icon: 'fire',
    color: '#DC143C',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 41,
    level: 41,
  },
  {
    id: 'level_up_42',
    title: 'Tierra Fértil',
    description: '¡Has alcanzado el nivel 42! Creas un espacio para crecer.',
    icon: 'earth',
    color: '#8B4513',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 42,
    level: 42,
  },
  {
    id: 'level_up_43',
    title: 'Aire Puro',
    description: '¡Has alcanzado el nivel 43! Respiras libertad y claridad.',
    icon: 'air-filter',
    color: '#B0C4DE',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 43,
    level: 43,
  },
  {
    id: 'level_up_44',
    title: 'Éter Infinito',
    description: '¡Has alcanzado el nivel 44! Conectado con todo.',
    icon: 'infinity',
    color: '#800080',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 44,
    level: 44,
  },
  {
    id: 'level_up_45',
    title: 'Equilibrio Perfecto',
    description: '¡Has alcanzado el nivel 45! Armonía en tu ser.',
    icon: 'scale-balance',
    color: '#32CD32',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 45,
    level: 45,
  },
  {
    id: 'level_up_46',
    title: 'Danza de la Vida',
    description: '¡Has alcanzado el nivel 46! Celebras cada paso.',
    icon: 'dance-ballroom',
    color: '#FF69B4',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 46,
    level: 46,
  },
  {
    id: 'level_up_47',
    title: 'Melodía Interior',
    description: '¡Has alcanzado el nivel 47! Tu alma canta en paz.',
    icon: 'music-note',
    color: '#6A5ACD',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 47,
    level: 47,
  },
  {
    id: 'level_up_48',
    title: 'Pincelada Maestra',
    description: '¡Has alcanzado el nivel 48! Creas tu propia obra de arte.',
    icon: 'brush',
    color: '#FFA500',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 48,
    level: 48,
  },
  {
    id: 'level_up_49',
    title: 'Escritor de Destinos',
    description: '¡Has alcanzado el nivel 49! Escribes tu propia historia.',
    icon: 'fountain-pen',
    color: '#4682B4',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 49,
    level: 49,
  },
  {
    id: 'level_up_50',
    title: 'Maestro Zen',
    description: '¡Has alcanzado el nivel 50! La paz interior es tuya.',
    icon: 'meditation',
    color: '#20B2AA',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 50,
    level: 50,
  },
  {
    id: 'level_up_51',
    title: 'Guardián de la Sabiduría',
    description: '¡Has alcanzado el nivel 51! Proteges el conocimiento.',
    icon: 'book-open-variant',
    color: '#4682B4',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 51,
    level: 51,
  },
  {
    id: 'level_up_52',
    title: 'Explorador de la Mente',
    description: '¡Has alcanzado el nivel 52! Descubres nuevos horizontes.',
    icon: 'compass-rose',
    color: '#708090',
    category: 'level-up',
    isUnlocked: (stats) => stats?.level >= 52,
    level: 52,
  },
];