services:
  - type: web
    name: mentali-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
